services:
  agendaonline-landing:
    build:
      dockerfile: ./apps/agendaonline-landing/Dockerfile
    ports:
      - '5000:4000'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
